### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by honzajavorek** [headpicker/headpicker.org#1]
The frontpage needs at least basic design.

**Comment by honzajavorek** [comment]
@TomasVotruba I was barely able to do #2 during the weekend. I'm not sure I'll be able to do this in any near future - PyCon is very soon and makes use of all my extra free time, if anything like extra free time even exists in my life.

**Comment by TomasVotruba** [comment]
Hi, thanks a lot for init!

I'm thinking of moving this under pehapkari.cz, because it's too much ogranizations and repositories for me at the moment. And it's slowly dying :/ 

Would you be ok with that? I could move there issues and you as well

**Comment by honzajavorek** [comment]
I'm okay with that :) Better living somewhere else than dying here.
