### ISSUE TITLE
Cartoons

### ISSUE THREAD

**Issue by honzajavorek** [headpicker/headpicker.org#2]
Cartoons are necessary to complement #1.

**Comment by honzajavorek** [comment]
@TomasVotruba My take on this:

![img_20160918_135909215-l](https://cloud.githubusercontent.com/assets/283441/18643414/48ca5f54-7ea5-11e6-8154-c2d4adfe6a5d.png)
![img_20160918_135909215-r](https://cloud.githubusercontent.com/assets/283441/18643416/494dde60-7ea5-11e6-94a5-2c923fc996e3.png)
![img_20160918_135941545](https://cloud.githubusercontent.com/assets/283441/18643426/4f38dd5c-7ea5-11e6-9e47-d19d7d4f3dbe.png)

I made this over the last weekend as part of my other works for the Python community.

[headpicker.zip](https://github.com/headpicker/headpicker.org/files/480777/headpicker.zip)

**Comment by TomasVotruba** [comment]
Moved https://github.com/pehapkari/pehapkari.cz/issues/70
